services:
  # PostgreSQL Database
  postgres:
    image: ayoubfetti/postgres
    container_name: helpdesk_postgres
    environment:
      POSTGRES_DB: helpdesk
      POSTGRES_USER: helpdesk_user
      POSTGRES_PASSWORD: helpdesk_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - helpdesk_network

  # Laravel Backend
  backend:
    image: ayoubfetti/helpdesk-backend
    container_name: helpdesk_backend
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=helpdesk
      - DB_USERNAME=helpdesk_user
      - DB_PASSWORD=helpdesk_password
      - APP_URL=http://localhost:8000
      - FRONTEND_URL=http://localhost:3000
      - SANCTUM_STATEFUL_DOMAINS=localhost:3000,127.0.0.1:3000,localhost,127.0.0.1
      - SESSION_DOMAIN=localhost
    depends_on:
      - postgres
    networks:
      - helpdesk_network

  # Vue.js Frontend
  frontend:
    image: ayoubfetti/helpdesk-frontend
    container_name: helpdesk_frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    networks:
      - helpdesk_network

volumes:
  postgres_data:
  backend_storage:

networks:
  helpdesk_network:
    driver: bridge
